---
title: "Functions and Packages in R"
subtitle: "Developing skills in R, DEEP, SU"
author: "Andreas Novotny"
date: "14 November 2018"
institute: NBIS, SciLifeLab
keywords: r, RaukR, markdown
output: 
  xaringan::moon_reader:
    
    encoding: 'UTF-8'
    self_contained: false
    chakra: 'remark-latest.min.js'
    css: 'presentation_noLogo.css'
    lib_dir: libs
    nature:
      ratio: '4:3'
      highlightLanguage: r
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: "deepRskills 2018 . %current%/%total%"

---
name: intro
class: spaced 

```{r,echo=FALSE,message=FALSE,warning=FALSE,results='hide'}
# run setup code

# load libraries ---------------------------------------------------------------
library(knitr) # runs pandoc
library(bookdown) # for markdown
library(captioner) # for table and figure captions

suppressPackageStartupMessages(library(tidyverse))

# knitr options ----------------------------------------------------------------

knitr::opts_knit$set(progress=TRUE,verbose=TRUE)
knitr::opts_chunk$set(dev="CairoPNG",results="hold",fig.show="hold",fig.align="left",echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,echo=FALSE,message=FALSE,warning=FALSE}
# load the packages you need

#library(tidyverse)
#library(ggplot2) # static graphics
```


## Do you use functions when coding?


```{r}
sqrt(4)
```

```{r}
print("Hello World")
```

```{r}
data.frame(x=numeric(), y=factor())
```
```{r}
c(1,2,3,4,5)
```

---
name: end-slide
class: end-slide

# Thank you